### ISSUE TITLE
Nuxt Internal Server error

### ISSUE THREAD

**Issue by arsley** [arsley/fidop-yakuman#2]
ログイン後、iOS上で更新ボタンを連打するとこのエラーをもらう。

```
[GET] /mahjong/games
20:14:38:83

WARN  Cannot stringify a function transformRequestWARN 
Cannot stringify a function transformResponseWARN
Cannot stringify a function httpAdapterWARN
Cannot stringify a function validateStatusWARN
Cannot stringify arbitrary non-POJOs ClientRequestWARN
Cannot stringify a function toJSONERROR
Maximum call stack size exceeded
at String.replace (<anonymous>)at stringifyPrimitive (node_modules/@nuxt/devalue/dist/devalue.cjs.js:207:20)at stringify (node_modules/@nuxt/devalue/dist/devalue.cjs.js:92:20)at node_modules/@nuxt/devalue/dist/devalue.cjs.js:129:98at Array.map (<anonymous>)at stringify (node_modules/@nuxt/devalue/dist/devalue.cjs.js:129:49)at node_modules/@nuxt/devalue/dist/devalue.cjs.js:129:98at Array.map (<anonymous>)at stringify (node_modules/@nuxt/devalue/dist/devalue.cjs.js:129:49)at node_modules/@nuxt/devalue/dist/devalue.cjs.js:129:98
```

**Comment by arsley** [comment]
原因?

ログインしていない状態で各ページにアクセスすると `axios.$get` がエラー (Unauthorized) になるが、このときのエラーハンドリングをしていない。
